name: CI

on:
  pull_request:
    branches: [ dev ]

jobs:      
  frontend:
    name: CI with Node.js
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: client
        
    strategy:
      matrix:
        node-version: [12.16.x]
    
    steps:
      - name: 체크아웃 Github-Action
        uses: actions/checkout@v2
        
      - name: node.js 12 설치 ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: process.env.CI 설정
        run: unset CI
 
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v2

      - name: npm 설치
        run: npm install

      - name: npm 빌드
        run: npm run build
